name: Workflow для main ветки

on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        run: docker login -u "andyshintar637" -p "${{ secrets.DOCKERHUB_TOKEN }}" docker.io
      - name: Build the Docker image
        run: docker build . -t andyshintar637/frontend:$(git rev-parse --short "$GITHUB_SHA")
      - name: Push the Docker image
        run: docker push andyshintar637/frontend:$(git rev-parse --short "$GITHUB_SHA")
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - id: ssh-context
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.HOST }}
          SSH_USER: ${{ secrets.USERNAME }}
          SSH_PASSWORD: ${{ secrets.PASSWORD }}
      - name: Login to Docker Hub
        run: docker login -u "andyshintar637" -p "${{ secrets.DOCKERHUB_TOKEN }}" docker.io
      - name: check
        run: pwd
      - name: check2
        run: ls
      - name: Update docker tag
        run: echo "IMAGE_TAG=$(git rev-parse --short "$GITHUB_SHA")" >> Frontend/.env
      - name: Kill previous deployment
        run: DOCKER_HOST=ssh://${{ steps.ssh-context.outputs.SERVER }} docker-compose -f Frontend/docker-compose.yaml -p deployment stop frontend
      - name: Recreate deployment
        run: DOCKER_HOST=ssh://${{ steps.ssh-context.outputs.SERVER }} docker-compose -f Frontend/docker-compose.yaml -p deployment up -d frontend